<?php

namespace Database\Seeders;

use App\Models\Customer;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class CustomerSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Clear existing customers
        Customer::truncate();
        
        $customers = [
            [
                'code' => 'CUST-001',
                'name' => 'Budi Santoso',
                'email' => 'budi@example.com',
                'phone' => '081234567890',
                'address' => 'Jl. Raya No. 123, Jakarta Timur',
                'livestock_type' => 'Ayam Broiler',
                'livestock_count' => 1000,
                'customer_type' => 'wholesale',
                'credit_limit' => 10000000,
                'current_debt' => 2500000,
                'allow_credit' => true,
                'payment_term_days' => 30,
                'loyalty_points' => 150,
                'total_purchases' => 25000000,
                'last_purchase_date' => now()->subDays(5),
                'is_active' => true,
            ],
            [
                'code' => 'CUST-002',
                'name' => 'Siti Aminah',
                'email' => 'siti@example.com',
                'phone' => '081234567891',
                'address' => 'Jl. Mawar No. 45, Bogor',
                'livestock_type' => 'Sapi Perah',
                'livestock_count' => 50,
                'customer_type' => 'wholesale',
                'credit_limit' => 15000000,
                'current_debt' => 5000000,
                'allow_credit' => true,
                'payment_term_days' => 45,
                'loyalty_points' => 200,
                'total_purchases' => 45000000,
                'last_purchase_date' => now()->subDays(3),
                'is_active' => true,
            ],
            [
                'code' => 'CUST-003',
                'name' => 'Ahmad Wijaya',
                'email' => 'ahmad@example.com',
                'phone' => '081234567892',
                'address' => 'Jl. Melati No. 67, Depok',
                'livestock_type' => 'Kambing',
                'livestock_count' => 25,
                'customer_type' => 'retail',
                'credit_limit' => 2000000,
                'current_debt' => 0,
                'allow_credit' => false,
                'payment_term_days' => 0,
                'loyalty_points' => 50,
                'total_purchases' => 3500000,
                'last_purchase_date' => now()->subDays(10),
                'is_active' => true,
            ],
            [
                'code' => 'CUST-004',
                'name' => 'Dewi Lestari',
                'email' => 'dewi@example.com',
                'phone' => '081234567893',
                'address' => 'Jl. Anggrek No. 89, Tangerang',
                'livestock_type' => 'Ayam Layer',
                'livestock_count' => 500,
                'customer_type' => 'wholesale',
                'credit_limit' => 8000000,
                'current_debt' => 1200000,
                'allow_credit' => true,
                'payment_term_days' => 30,
                'loyalty_points' => 120,
                'total_purchases' => 18000000,
                'last_purchase_date' => now()->subDays(2),
                'is_active' => true,
            ],
            [
                'code' => 'CUST-005',
                'name' => 'Rudi Hermawan',
                'email' => 'rudi@example.com',
                'phone' => '081234567894',
                'address' => 'Jl. Kenanga No. 12, Bekasi',
                'livestock_type' => 'Ayam Kampung',
                'livestock_count' => 100,
                'customer_type' => 'retail',
                'credit_limit' => 1000000,
                'current_debt' => 0,
                'allow_credit' => false,
                'payment_term_days' => 0,
                'loyalty_points' => 30,
                'total_purchases' => 2200000,
                'last_purchase_date' => now()->subDays(7),
                'is_active' => true,
            ],
            [
                'code' => 'CUST-006',
                'name' => 'Indra Gunawan',
                'email' => 'indra@example.com',
                'phone' => '081234567895',
                'address' => 'Jl. Flamboyan No. 34, Cibinong',
                'livestock_type' => 'Bebek',
                'livestock_count' => 200,
                'customer_type' => 'wholesale',
                'credit_limit' => 5000000,
                'current_debt' => 800000,
                'allow_credit' => true,
                'payment_term_days' => 21,
                'loyalty_points' => 80,
                'total_purchases' => 8500000,
                'last_purchase_date' => now()->subDays(4),
                'is_active' => true,
            ],
            [
                'code' => 'CUST-007',
                'name' => 'Ratna Sari',
                'email' => 'ratna@example.com',
                'phone' => '081234567896',
                'address' => 'Jl. Dahlia No. 56, Cikarang',
                'livestock_type' => 'Ikan Lele',
                'livestock_count' => 5000,
                'customer_type' => 'wholesale',
                'credit_limit' => 12000000,
                'current_debt' => 3500000,
                'allow_credit' => true,
                'payment_term_days' => 30,
                'loyalty_points' => 180,
                'total_purchases' => 22000000,
                'last_purchase_date' => now()->subDays(1),
                'is_active' => true,
            ],
            [
                'code' => 'CUST-008',
                'name' => 'Hendra Kusuma',
                'email' => 'hendra@example.com',
                'phone' => '081234567897',
                'address' => 'Jl. Cempaka No. 78, Karawang',
                'livestock_type' => 'Sapi Potong',
                'livestock_count' => 30,
                'customer_type' => 'wholesale',
                'credit_limit' => 20000000,
                'current_debt' => 7500000,
                'allow_credit' => true,
                'payment_term_days' => 60,
                'loyalty_points' => 250,
                'total_purchases' => 55000000,
                'last_purchase_date' => now()->subDays(6),
                'is_active' => true,
            ],
            [
                'code' => 'CUST-009',
                'name' => 'Maya Putri',
                'email' => 'maya@example.com',
                'phone' => '081234567898',
                'address' => 'Jl. Teratai No. 90, Purwakarta',
                'livestock_type' => 'Ayam Broiler',
                'livestock_count' => 300,
                'customer_type' => 'retail',
                'credit_limit' => 3000000,
                'current_debt' => 500000,
                'allow_credit' => true,
                'payment_term_days' => 14,
                'loyalty_points' => 60,
                'total_purchases' => 5500000,
                'last_purchase_date' => now()->subDays(8),
                'is_active' => true,
            ],
            [
                'code' => 'CUST-010',
                'name' => 'Agus Setiawan',
                'email' => 'agus@example.com',
                'phone' => '081234567899',
                'address' => 'Jl. Kamboja No. 12, Subang',
                'livestock_type' => 'Domba',
                'livestock_count' => 40,
                'customer_type' => 'retail',
                'credit_limit' => 2500000,
                'current_debt' => 0,
                'allow_credit' => false,
                'payment_term_days' => 0,
                'loyalty_points' => 40,
                'total_purchases' => 4200000,
                'last_purchase_date' => now()->subDays(12),
                'is_active' => true,
            ],
        ];

        foreach ($customers as $customerData) {
            Customer::create($customerData);
        }
        
        $this->command->info('✅ Customers seeded successfully');
    }
}
